In [2]:
!pip install numpy 
import numpy as np

NumPy is mainly used because it allows vectoriation of a list and makes operations faster.


**CREATING A ARRAY**

In [ ]:
#Creating Arrays

#1. Converting a list into arrays
arr1 = np.array([1,2,3,4,5])
print("Using method 1 of creating a list : ",arr1)

arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print("Creating a 2D array : \n",arr2)

# 2.Using arrange() function like in python
# creates an array using (x,y,z) where x is lower limit (inclusive), y is upper limit (exclusive), z represents jumps
arr3 = np.arange(1,20,2)
print("Using method 2  - using arrange function : ",arr3)

# 3. Using linspace function - 
arr4 = np.linspace(0,30,3)      #0 - 20 with a total of 3 elements
print("Using method 3 - using linspace function : ",arr4)

arr5 = np.zeros((3,3))
print("Using method 4 - using zeros function : \n",arr5)
arr6 = np.ones((3,3))
print("Using method 5 - using ones function : \n",arr6)

#5. Creating an array of (x,y) dimension with value of user's choice
arr7 = np.full((3,3),5)
print("Using method 6 - using full function : \n",arr7)

#6. Identity Matrix
I = np.identity(3)
print("Using method 7 - using identity function : \n",I)

#7. Diagonal Matrix
D = np.diag([1,2,3])
print("Using method 8 - using diag function : \n",D)

#8. Random Matrix
arr8 = np.random.randint(1,10,(3,3))        #1 - 10 with a total of 3x3 elements : LowerLimit, UpperLimit, Dimension
print("Using method 9 - using random function : \n",arr8)

Using method 1 of creating a list :  [1 2 3 4 5]
Creating a 2D array : 
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Using method 2  - using arrange function :  [ 1  3  5  7  9 11 13 15 17 19]
Using method 3 - using linspace function :  [ 0. 15. 30.]
Using method 4 - using zeros function : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Using method 5 - using ones function : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Using method 6 - using full function : 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Using method 7 - using identity function : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Using method 8 - using diag function : 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Using method 9 - using random function : 
 [[9 9 8]
 [1 1 7]
 [6 8 8]]


**INDEXING AND SLICING AN ARRAY**

In [ ]:
arr = [1,2,3,4,5,5,6,7,8,9,10]
print(arr[0])          #First element           -       1
print(arr[-1])         #Last element            -       10

print(arr[1:4])        #Elements from index 1 to 3                              -       [2,3,4]
print(arr[1:4:2])      #Elements from index 1 to 3 with a step of 2             -       [2,4]

print(arr[:3])        # from start till index 2                                 -       [1,2,3]
print(arr[2:])        # from index 2 to end)                                    -       [3,4,5,6,7,8,9,10]  
print(arr[::-1])      # from end to start - REVERSED                            -       [10,9,8,7,6,5,4,3,2,1]


1
10
[2, 3, 4]
[2, 4]
[]
[1, 2, 3]
[3, 4, 5, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 5, 4, 3, 2, 1]


For a 2D Array,

In [ ]:
import numpy as np
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2d[0, 1])              # Access element at row 0, column 1
print(arr2d[1, 2])              # Access element at row 1, column 2

print(arr2d[0])                 # Access entire row 0
print(arr2d[1])                 # Access entire row 1




2
6
[1 2 3]
[4 5 6]


Intersting array : 

In [ ]:
arr9 = np.arange(20)
a = arr9[-9:15:3]
print(a)

#Creates an array from 0-19
#arr9[-9:15:3] means start from -9th index(arr[11]), end at 15th index(arr[14]), and jump by 3

[11 14]


Some Functions : 

In [ ]:
#Reshape : 
m = np.array([1,2,3,4,5,6,7,8])
new = m.reshape(2,2,2)                  #
print(new,'\n')

s = np.array([[1,2,3,4,5,6,7,8], [10,20,30,40,50,60,70,80]])
print(s.transpose())

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]
 [ 7 70]
 [ 8 80]]


Intersting Array : 

In [26]:
a = np.arange(6)       # Step 1
b = a.reshape(2, 3)    # Step 2         #Reshapes into 2 rows and 3 columns
c = b[1] + 2           # Step 3         #Adds 2 to the second row
d = c.reshape(3, 1)    # Step 4         #Reshapes into 3 rows and 1 column

print(d)               # Final output

[[5]
 [6]
 [7]]


**DOT PRODUCT :**

In [21]:
a = np.array([1, 2])
b = np.array([3, 4])
dotpr = np.dot(a, b)
print("Dot product:", dotpr)

# 2D matrix dot product
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("2D Matrix Dot Product :\n", np.dot(A, B))

Dot product: 11
2D Matrix Dot Product :
 [[19 22]
 [43 50]]
